#!/bin/sh

usage() {
	cat <<EOF
usage: mkinitramfs [-h]
    mkinitramfs -a <initramfs> -i <init> -c <candidates>
EOF
	exit $1
}

set -e

while getopts ha:i:c: opt
do
	case $opt in
	h) usage 0 ;;
	a) initramfs="$PWD/$OPTARG" ;;
	i) init="$PWD/$OPTARG" ;;
	c) candidates="$PWD/$OPTARG" ;;
	*) usage 1 ;;
	esac
done

if [ -z $initramfs ] || [ -z $init ] || [ -z $candidates ]
then usage 1
fi

if [ `id -u` -ne 0 ]
then
	echo "$0 must be used as root"
	exit 1
fi

tempdir=`mktemp -d /tmp/mkinitramfs.XXXXXX`
cd "$tempdir"

if mkdir dev mnt &&
	cp "$candidates" candidates &&
	cp "$init" init &&
	chown -R 0:0 "$tempdir" &&
	find . | cpio -oH newc | gzip -9 > "$initramfs"
then echo "Created $initramfs"
else echo "Unable to create initramfs"
fi

cd
rm -rf "$tempdir"

