#!/bin/sh

usage() {
	cat <<EOF
usage: mkinitramfs [-h]
    mkinitramfs -a <initramfs> -i <init> -c <candidates>
EOF
	exit $1
}

while getopts ha:i:c: opt
do
	case $opt in
	h) usage 0 ;;
	a) initramfs="`pwd`/$OPTARG" ;;
	i) init="`pwd`/$OPTARG" ;;
	c) candidates="`pwd`/$OPTARG" ;;
	*) usage 1 ;;
	esac
done

[ -z $initramfs ] && usage 1

mkinitramfs_cp_init() {
	if [ ! -z "$1" ]
	then
		if mkdir dev mnt && cp "$init" init
		then return 0
		else return 1
		fi
	else return 0
	fi
}

mkinitramfs_cp_candidates() {
	if [ ! -z "$1" ]
	then
		cp "$1" candidates
		return $?
	else return 0
	fi
}

if tempdir=`mktemp -d /tmp/mkinitramfs.XXXXXX`
then
	cd "$tempdir"

	if mkinitramfs_cp_init "$init" &&
		mkinitramfs_cp_candidates "$candidates" &&
		find . | cpio -oH newc | gzip -9 > "$initramfs"
	then echo "Created $initramfs"
	else echo "Unable to create initramfs"
	fi

	cd && rm -rf "$tempdir"
fi

